capp/models.py
from capp import db 
from datetime import datetime
from capp import login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

# Database User
class User(db.Model, UserMixin):
    __tablename__ = "user_table"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    transport = db.relationship('Transport', backref='author', lazy=True)

# Database Transport
class Transport(db.Model):
    __bind_key__ = 'transport'
    __tablename__= 'transport_table'
    id = db.Column(db.Integer, primary_key=True)
    kms = db.Column(db.Float)
    transport = db.Column(db.String)
    fuel = db.Column(db.String)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    co2= db.Column(db.Float)
    total = db.Column(db.Float)  
    user_id = db.Column(db.Integer, db.ForeignKey('user_table.id'), nullable=False)

capp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from capp.models import User



class RegistrationForm(FlaskForm):
  username = StringField('Username', 
                         validators=[DataRequired(), Length(min=2, max=30)])
  email = StringField('Email',
                      validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  confirm_password = PasswordField('Confirm Password',
                      validators=[DataRequired(), EqualTo('password')])                                
  submit = SubmitField('Sign Up')
  def validate_username(self, username):
    user = User.query.filter_by(username=username.data).first()
    if user:
        raise ValidationError('That username is taken. Please choose a different one.')

  def validate_email(self, email):
    email = User.query.filter_by(email=email.data).first()
    if email:
        raise ValidationError('That email is taken. Please choose a different one.')

class LoginForm(FlaskForm):
  email = StringField('Email',
                      validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  remember = BooleanField('Remember Me')
  submit = SubmitField('Login')  

capp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
import os
from flask_login import LoginManager


application = Flask(__name__)

application.config['SECRET_KEY'] = os.environ['SECRET_KEY']  


# databases for users and transport 
application.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///user.db'
application.config['SQLALCHEMY_BINDS'] ={'transport': 'sqlite:///transport.db'}

db = SQLAlchemy(application)
bcrypt = Bcrypt(application)
login_manager= LoginManager(application)
login_manager.login_view = 'users.login'
#login_manager.login_message_category = 'info'

from capp.home.routes import home
from capp.methodology.routes import methodology
from capp.carbon_app.routes import carbon_app
from capp.users.routes import users

application.register_blueprint(home)
application.register_blueprint(methodology)
application.register_blueprint(carbon_app)
application.register_blueprint(users)

capp/carbon_app/__init__.py
#

capp/carbon_app/routes.py
from flask import render_template, Blueprint
from capp.models import Transport
from flask_login import login_required

carbon_app=Blueprint('carbon_app',__name__)

@carbon_app.route('/carbon_app')
def carbon_app_home():
    return render_template('carbon_app/carbon_app.html', title='carbon_app')

@carbon_app.route('/carbon_app/new_entry')
@login_required
def new_entry_home():
    return render_template('carbon_app/new_entry.html', title='new_entry')

@carbon_app.route('/carbon_app/your_data')
@login_required
def your_data_home():
    return render_template('carbon_app/your_data.html', title='your_data')
    

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint
from capp.models import User, Transport

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  # Query 1: Kilometers by user
  username = 'Fjell'
  user_id = User.query.filter_by(username=username).first().id
  user_name= User.query.filter_by(username=username).first().username
  user_transports = Transport.query.filter_by(user_id=user_id).all()
 
  # Query 2: Co2 per kilometer by user 
  username = 'Fjell'
  user_id = User.query.filter_by(username=username).first().id
  user_name= User.query.filter_by(username=username).first().username
  user_transports = Transport.query.filter_by(user_id=user_id).all()
  kms = []
  co2 = []
  for transport in user_transports:
    (kms.append(round(transport.kms)))
    (co2.append(round(transport.co2)))  
  co2_kms = []
  len_list = len(kms)
  for i in range(len_list):
      co2_kms.append(round((co2[i]/kms[i]),3))
 

  return render_template('home.html', user_transports=user_transports, user_name=user_name, kms=kms, 
                         co2=co2, co2_kms=co2_kms)

capp/methodology/__init__.py
#

capp/methodology/routes.py
from flask import render_template, Blueprint

methodology=Blueprint('methodology',__name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

capp/users/__init__.py
#

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for, request
from capp.users.forms import RegistrationForm, LoginForm
from capp.models import User
from capp import db, bcrypt
from flask_login import login_user, current_user, logout_user

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
      user_hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
      user = User(username=form.username.data, email=form.email.data, password=user_hashed_password)
      db.session.add(user)
      db.session.commit()
      flash('Your account has been created! Now, you are able to login!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if current_user.is_authenticated:
        return redirect(url_for('home.home_home'))
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
        login_user(user, remember=form.remember.data)
        next_page=request.args.get('next')
        flash('You have logged in! Now, you can start to use the carbon app!', 'success')
        return redirect(next_page) if next_page else redirect(url_for('home.home_home'))
    else:
        flash('Login Unsuccessful. Please check email and password!', 'danger')  
  return render_template('users/login.html', title='login', form=form)

@users.route('/logout')
def logout():    
    logout_user()
    flash('You have logged out', 'success')
    return redirect(url_for('home.home_home'))

capp/templates/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
        <div class="header_carbon_app">
            <div class="box"> 
            <h1 style="font-size:55px;"><span class="text-logo"> Carbon App Calculator</span></h1>
            <p style="text-align:left">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
            </p>
            <div class="container_buttons_links_header_carbon_app">
                <div class="btn">
                    <a href="{{url_for('methodology.methodology_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">Methodology</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;", data-toggle="modal" data-target="#carbon_app_instructions">Instructions</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">Your emissions</a>
                </div>
            </div>  
            <!-- Modal Instructions -->
            <div class="modal fade" id="carbon_app_instructions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
          
                    <div class="modal-header">
                    <h5 class="modal-title", style="color:#888870; text-align: center;">Instructions</h5>
                    </div>
          
                    <div class="modal-body", style="color:#888870">
                    <p style="text-align: left;">
                        To use this carbon app, you need to know what kind of transportation you have been using the last 7 days. 
                    </p>
                    <ol style="text-align:left;">
                        <li>
                            Write in how many km you have been traveling for with one kind of transportation.
                        </li>
                        <li>
                            Select type of transportation.
                        </li>
                        <li>
                            Select fuel of the transportation.
                        </li>
                        <li>
                            Submit.
                        </li>
                    </ol>
                    </div>
          
                    <div class="modal-footer">
                    <button class="btn btn-secondary btn-lg mr-2", style="background-color:#888870;" data-dismiss="modal">Close</button>
                    </div>
          
                </div>
                </div>
            </div>
            </div>
            <div class="box">
            <img 
                src="{{url_for('static', filename='icons/Carbon_calculator_3.svg')}}"
                width="325" 
                height="325"
                alt=""/>
            </div>
        </div>
        
        </div>
    </section> 
       

{% endblock content %}

capp/templates/carbon_app/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
    <section class="section_header_carbon_app">
        <div class="container">
    
        <div class="header_carbon_app">
            <div class="box"> 
            <h1 style="font-size:55px;"><span class="text-logo"> Carbon App Calculator</span></h1>
            <p style="text-align:left;">
                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat dolores quos asperiores repellendus facilis cum illo aperiam odit doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente quisquam consectetur optio magnam voluptates omnis vel officia alias distinctio quas laborum reiciendis ratione inventore veniam, cupiditate doloribus dolore, eius natus a. Magni inventore consequuntur voluptas reprehenderit perferendis! Molestias aspernatur rem autem aut temporibus.
            </p>
            <div class="container_buttons_links_header_carbon_app">
                <div class="btn">
                    <a href="{{url_for('methodology.methodology_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">Methodology</a>
                </div>
                <div class="btn">
                    <a href="#" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;", data-toggle="modal" data-target="#carbon_app_instructions">Instructions</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.new_entry_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">New entry</a>
                </div>
                <div class="btn">
                    <a href="{{url_for('carbon_app.your_data_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">Your data</a>
                </div>
            </div>  
            <!-- Modal Instructions -->
            <div class="modal fade" id="carbon_app_instructions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
          
                    <div class="modal-header">
                    <h5 class="modal-title", style="color:black; text-align: center;">Carbon App, instructions</h5>
                    </div>
          
                    <div class="modal-body", style="color:black">
                    <p style="text-align: left;">
                        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Repudiandae ratione tempore id esse nobis molestias quasi explicabo possimus ea reprehenderit.
                    </p>
                    <ol style="text-align:left;">
                        <li>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, sint.
                        </li>
                        <li>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi, sint.
                        </li>
                    </ol>
                    </div>
          
                    <div class="modal-footer">
                        <a href="{{url_for('carbon_app.new_entry_home')}}" class="btn btn-primary btn-lg mr-2", style="background-color:#FF7F00;">New entry</a>
                        <button class="btn btn-secondary btn-lg mr-2", style="background-color:#6c757d;" data-dismiss="modal">Close</button>
                    </div>
          
                </div>
                </div>
            </div>
            </div>
            <div class="box">
            <img 
                src="{{url_for('static', filename='icons/Carbon_calculator_3.svg')}}"
                width="325" 
                height="325"
                alt=""/>
            </div>
        </div>
        
        </div>
    </section> 
       

{% endblock content %}

capp/templates/carbon_app/new_entry.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section>
  <div class="container">
   
    <h1>New entry:</h1>

  </div>
</section> 

        
{% endblock content %}

capp/templates/carbon_app/your_data.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section>
  <div class="container">

    <h1>Your data:</h1>

  </div>
</section> 

        
{% endblock content %}

capp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
      <!-- Font Awesome code -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

 
      <!--Import the Bootstrap CSS file:-->
 <link
 href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
 rel="stylesheet"
 integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
 crossorigin="anonymous"
 />
 <link
   rel="stylesheet"
   href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
 />

 <!-- Matjax -->
 <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
 <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

      <!-- CSS code -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user.css') }}">

      <!-- To activate media queries in devices -->
      <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">
        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>home</title>
        {% endif %}

    </head>
    <body>
    
        <section class="section_navbar">
          <br>
          <div class="container">
            <div class="navbar">
              <h1 class="logo">
                <a href="{{url_for('home.home_home')}}">
                  <span class="text-logo" style="font-size: 50px;"><i class="fa-solid fa-leaf" style="color: #FF7F00;"></i> CarbonApp</span>
              </a>
              </h1>
              {% if current_user.is_authenticated %}
              <nav>
                <ul>
                    <li>
                        <a href="{{url_for('home.home_home')}}"><i class="fa-solid fa-house"></i> Home</a>
                    </li>
                    <li>
                        <a href="{{url_for('methodology.methodology_home')}}"> <i class="fa-solid fa-info"></i> Methodology</a>
                    </li>
                    <li>
                        <a href="{{url_for('carbon_app.carbon_app_home')}}"> <i class="fa-solid fa-calculator"></i> Carbon App</a>
                    </li>
                    <li>
                      <a href="{{url_for('users.logout')}}"> <i class="fa-solid fa-arrow-right-to-bracket"></i> Logout</a>
                  </li>
                    
                </ul>
              </nav> 
              {%else%}
              <nav>
                <ul>
                    <li>
                        <a href="{{url_for('home.home_home')}}"><i class="fa-solid fa-house"></i> Home</a>
                    </li>
                    <li>
                        <a href="{{url_for('methodology.methodology_home')}}"> <i class="fa-solid fa-info"></i> Methodology</a>
                    </li>
                    <li>
                        <a href="{{url_for('carbon_app.carbon_app_home')}}"> <i class="fa-solid fa-calculator"></i> Carbon App</a>
                    </li>
                    <li>
                      <a href="{{url_for('users.register')}}"> <i class="fa-regular fa-address-card"></i> Register</a>
                  </li>
                    <li>
                      <a href="{{url_for('users.login')}}"> <i class="fa-solid fa-arrow-right-to-bracket"></i> Login</a>
                    </li>
                </ul>
              </nav>
              {%endif%}
              
            </div>
          </div>
          <br>
        </section>

        {% block content %} {% endblock %}
        <section class="section_footer">
          <div class="container">
            <div class="footer">
              <br>
              <br>
            <div class="icon-footer" style="text-align: center;">
              <h1>
                Carbon App 
                <a href="#">
                  <i class="fa-solid fa-circle-up" style="color: #FF7F00"></i>
                </a>
                <br>
                <br>
              </h1>
            </div>
            </div>
          </div>
        </section>

        <!-- Bootstrap -->
        <!-- Question Accordion -->
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"
        ></script>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
    </body>
</html>

capp/templates/methodology.html
<!-- Colors 
Home, section 1 (header, background): #698269
Home, section 1 (header, boxes): #B99B6B
Home, section 2 (developers, background): #F1DBBF 
Home, section 2 (developers, boxes): #AA5656 
*/ -->

{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_methodology">
    <div class="container">
  
      <div class="header">
        <div class="box"> 
          <h1 style= "font-size:55px;"><span class=text-logo> Methodology</span></h1>
          <p style="text-align:left;">
                  
            <br>Here you can find our methodology for gathering data for the Carbon App.
            The methodology for the Carbon App is based on real data on carbon emission. The students has been critical and search for sicens based data. The development of the formulas are made by the students and are explained. We hope that this Carbon app will help people to be more aware of their carbon emission on a daily basis, and hopefully reduce it.
          </p>
            <button class="btn">
                <a href="https://docs.google.com/document/d/1LB7sJ2ddfoHPvye0LtYxO5xrmzEQeNHj2j6Ac6Gt_8c/edit?fbclid=IwAR3QH5EGtb0Qicoog0iJNQiYWfmuadTB3eiiieQOIfvOQS1CTFyBkUBR96I" class="button" target="_blank">Paper</a>
            
            
                <a href="{{url_for('carbon_app.carbon_app_home')}}" class="button">Carbon App</a>
            </button>
        </div>
        <div class="box">
          <img 
            src="{{url_for('static', filename='icons/methodology_photo.png')}}"
            width="325" 
            height="337"
            alt=""/>
        </div>
      </div>
      
    </div>
</section> 

<!-- Transports -->
<section class="section_transports">
    <div class="container">
   
      <div class="transports" style="display:block;">
        <br>
        <div class="box">
          <h1 style="text-align:center;"> Our methodology</h1>
          <p>
            Our group developed an app that calculates carbon emissions from transport to help individuals make informed decisions about their travel choices. 
            To find the nessesary data and statistics to calculate the emission, we used a carbon footprint analysis. This methodology involves calculating the total greenhouse gas emission associated with different transport alternatives. By using a carbon footprint analysis we can provide a comprehensive view of an individual's environmental impact, including indirect and direct emission. 

          </p>      
        </div>
      </div>
   
      <div class="transports" style="text-align: left;">
          <div class="container">
            <div class="box">
   
              <h3>Cars</h3>
              <p>
                Gasoline:
                <br>According to SSB.no, an avarage gasoline driven car emits <br>157,47g CO\(_2\) per km.
                <br><br>\[{0,157kg \times km} \over Passengers \]
                
                Diesel:
                <br>According to SSB.no, an avarage diesel driven car emits <br>130,09g CO\(_2\) per km.
                <br><br>\[{0,130kg \times km} \over Passengers \]
                Hybrid:
                <br>From transportsenvironment.org there has been estimated that an avarage hybrid plug in car emits 152g CO\(_2\) per km.
                <br><br>\[{0,152kg \times km} \over Passengers \]
                Electric:
                <br>According to SSB.no, an avarage electrical driven car consumes 
                <br>0,2 kWh per km. Generating 1 kWh with fossil fuels emits 0,388 kg of CO\(_2\)
                <br><br>\[{0,2 kWh \times km \times 0,388 kg CO_2} \over Passengers \]
              </p>
            </div>
            <div class="box">
              <h3>Busses</h3>
              <p>
                Diesel:
                <br>According to SSB.no, an avarage diesel driven bus emits <br>855,4g CO\(_2\) per km.
                <br><br>\[{0,855kg \times km} \over Passengers \]
                Biodiesel:
                <br>According to framtiden.no an avarge biodiesel driven bus emits 14g of CO\(_2\) per person km. 
                <br><br>\[{0,014kg \times km}\]
                Electric:
                <br>According to Sustainable-bus.com, an avarage electrical driven bus consumes 
                1,745 kWh per km. Generating 1 kWh with fossil fuels emits 0,388 kg of CO\(_2\)
                <br><br>\[{1,745 kWh \times km \times 0,388 kg CO_2} \over Passengers \]
            </div>

              

   
   
          </div>
          <div class="container" style="margin: 0;">
            <div class="box2">
              <h3>Other electrical transports:</h3>
              <p>
                A grown man that weighs 80kg and is 180cm tall, bicycling in the city
                <br>will use energy worth of 0,037 kWh. (here we could convert to juuls and tell how much he would need to eat??)
                <br><br>
                El-kick-scooter:
                <br>Electrical Two Wheels states in their product catalog that their El-kick-scooter on an avarage 
                consumes 0,006kWh. Generating 1 kWh with fossil fuels emits 0,388 kg of CO\(_2\).
                <br><br>\[0,006 kWh \times km \times 0,388 kg CO_2\]
                El-bycycle:
                <br>According to tredz.co.uk, an electrical bike with maximum capacity of 400 Wh will be last for 80km
                on an open road, with good road surfaces and a steady pace. \({400 Wh \over 80km} = 5 Wh = 0,005 kWh \)
                per km. Generating 1 kWh with fossil fuels emits 0,388 kg of CO\(_2\)
                <br><br>\[0,005 kWh \times km \times 0,388 kg CO_2\]

              </p>
            </div>
            <div class="box2">
              <h3>Airplain</h3>
              <p>
                Business class:
                According to framtiden.no, each person sitting in business class is responsible for 298g of CO\(_2\) per km.
                <br><br>\[{0,298kg \times km}\]
                Economy class:
                According to framtiden.no, each person sitting in economy class is responsible for 133g of CO\(_2\) per km.
                <br><br>\[{0,133kg \times km}\]
              </p>
            </div>           
            <div class="box2">
              <h3>Walk</h3>
    
              <p>
                A grown man that weighs 80kg and is 180cm tall, walking in a pace of 4 km/h
                will use energy worth of 0,065 kWh. (here we could convert to juuls and tell how much he would need to eat??)
    
              </p>
            </div>         
            <div class="box">
              <h3>Trains</h3>
              <p>
                According to framtiden.no an avarage train emits 45g of CO\(_2\) per person km.
                <br><br>\[{0,045kg \times km}\]
              </p>
                
            </div> 
          </div>
      
        </div>
      </div>
    </div>          
  </section>
   
  {% endblock content %}

capp/templates/users/login.html
{% extends "layout.html" %}
{% block content %}

<section class="register_section_css">
  <div class="container">
          <div class="box">

          </div>
          <div class="box">
              
              <form method="POST" action="">
                  {{ form.hidden_tag() }}
                      <fieldset class="form-group">
                          <legend class="border-bottom mb-4">Log In</legend>
                          <div class="form-group">
                              {{ form.email.label(class="form-control-label") }}
                              {% if form.email.errors %}
                                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                                  <div class="invalid-feedback">
                                      {% for error in form.email.errors %}
                                          <span>{{ error }}</span>
                                      {% endfor %}
                                  </div>
                              {% else %}
                                  {{ form.email(class="form-control form-control-lg") }}
                              {% endif %}
                          </div>
                          <div class="form-group">
                              {{ form.password.label(class="form-control-label") }}
                              {% if form.password.errors %}
                                  {{ form.password(class="form-control form-control-lg is-invalid") }}
                                  <div class="invalid-feedback">
                                      {% for error in form.password.errors %}
                                          <span>{{ error }}</span>
                                      {% endfor %}
                                  </div>
                              {% else %}
                                  {{ form.password(class="form-control form-control-lg") }}
                              {% endif %}
                          </div>
                          <div class="form-check">
                              {{ form.remember(class="form-check-input",style="text-align: left;") }}
                              {{ form.remember.label(class="form-check-label",style="text-align: left;") }}
                          </div>
                      </fieldset>
                      </br>
                      <div class="form-group">
                          {{ form.submit(class="btn btn-outline-info") }}
                      </div>
              </form>
              </br>
              <div class="border-top pt-3">
                  <small>
                      Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
                  </small>
              </div>

          </div>
          <div class="box">

          </div>
  </div>
</section>

        
{% endblock content %}